### PR TITLE
fix: updated borders for both dark and light mode

### LINKED ISSUE #636: UI issue in pricing and feature section in dark mode
In dark mode the pricing section's border are not clearly visible
Screenshot (100)

Also it'll be nice if we add some border to each features in feature section.
Screenshot (99)

### PR DESCRIPTION
**Pull request by shreyas0924**
Fixes #636 

I have included borders that correspond to both the light and dark themes. It includes UI for features, pricing and FAQ section

image
image

### CODE REVIEW

File: components/defaultLanding/FeatureSection.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import features from './data/features.json';
 const FeatureSection = () => {
   const { t } = useTranslation('common');
   return (
-    <section className="py-6 px-2">
+    <section className="py-6 px-2 ">
```
Comment (devkiran) [inline components/defaultLanding/FeatureSection.tsx:8]: @shreyas0924 Can you remove this unnecessary space?

File: components/defaultLanding/FeatureSection.tsx [hunk 2]
```diff
@@ -14,12 +14,15 @@ const FeatureSection = () => {
           Lorem Ipsum is simply dummy text of the printing and typesetting
           industry.
         </p>
-        <div className="flex items-center justify-center">
-          <div className="grid grid-cols-1 xl:grid-cols-3 md:grid-cols-2">
+        <div className="flex items-center justify-center  ">
```
Comment (devkiran) [inline components/defaultLanding/FeatureSection.tsx:17]: Can you remove this extra space?

File: components/defaultLanding/FeatureSection.tsx [hunk 3]
```diff
@@ -14,12 +14,15 @@ const FeatureSection = () => {
...
+          <div className="grid grid-cols-1 xl:grid-cols-3 md:grid-cols-2 gap-2">
             {features.map((feature: any, index) => {
               return (
-                <div className="card-compact card" key={index}>
-                  <div className="card-body">
+                <div
+                  className="card-compact card dark:border-gray-200 border border-gray-300"
+                  key={index}
+                >
+                  <div className="card-body ">
```
Comment (devkiran) [inline components/defaultLanding/FeatureSection.tsx:25]: here as well.

**Review by devkiran — CHANGES_REQUESTED** [review]
LGTM. @shreyas0924 Mentioned some formatting changes.

**Review by devkiran — APPROVED** [review]
